Update Tests to Catch Up with App Changes
maidsafe/sn_cli pull request #67
Opened 2021-08-13 14:44 UTC by jacderida

### tests: Amend and Provide More Utils
    
In the process of updating the tests to catch up with the application, some functions in the test helper library have been added, some have been removed, and some have been changed:
    
* The `--preload` arg was removed from the `keys create` command so the helper function was updated to accomodate that.
* The `wallet` command was entirely removed, so the helper function for creating one was removed.
* The function for executing a command was modified to use assert_cmd, because the newer version of this outputs both the stdout and stderr for the command. This is important because a lot of commands are run to setup the context for a test, and the `cmd!` macro from duct doesn't output the failure.
    
The assert_cmd and predicates crates were updated to support those changes.

### tests: Update Tests to Catch Up with App Changes
    
There were several changes required to bring the tests up-to-date with changes that were made in the application. Of all the tests that are now enabled to run, I've seen them complete at least once. However, if you try to run the whole suite, a significant percentage of the tests will still fail sporadically.
    
There are a few tests that have been identified that fail consistently: those have been marked with ignore attributes and need to be fixed.
    
The main, notable changes made for catch up are as follows:
    
* Remove the use of the 'safe://' prefix in NRS strings.
* Small changes in the format of error messages from the safe API.
* For files based tests, contents of test data was updated and hard coded values for things like sizes were changed to read the test data dynamically.
* For files and a few other test categories, the use of the duct cmd! macro has been replaced in favour of the safe_cmd helper function, which will output stdout and stderr for failed commands.
* Wallet tests and benchmarks completely removed since commands related to wallets have been removed.
* Tests related to the `keypair`, `keys balance` and `keys transfer` have also been removed, since these commands no longer exist.
    
The tests have also been configured to use Color Eyre, which is useful for more detailed error output.

### tests: Replace all cmd! Macros
    
These are all replaced with use of `safe_cmd` or `safe_cmd_stdout`, which both use assert_cmd. This means you'll always get the output for failed commands and you can see why the commands failed, if they do.

### tests: Schedule Network Tests to Run Nightly
    
All of the tests that haven't been marked with ignore can run successfully; however, they're all still subject to sporadic failures.
    
For this reason, they are disabled from running on PRs, but we can run them every night until we can get them running stable. If we keep our eye on the nightly runs, we can at least keep the tests up-to-date with changes in the application.

Finally, there's a commit for fixing misc clippy warnings.

2021-08-13 16:24 UTC, connec requested changes
Looks good to me! I've left a couple of queries regarding when `color_eyre` is installed, and an extraneous assignment in a shell script, which are the only things I'd consider 'blocking'.

Also left a few more nitpicky suggestions, which you should feel free to take or leave 😄

2021-08-13 16:24 UTC, connec commented on sn_cmd_test_utilities/src/lib.rs
> +    /// Runs safe with the arguments specified, with the option to assert on the exit code.
Nitpick: It's good practice to separate a header and body in doc comments, similarly to commit messages. These are used by docs.rs to print useful previews etc. For example, see the current [`sn_api`](https://docs.rs/sn_api/0.34.1/sn_api/#enums) docs. Not only does it look a bit off in the table of contents, if you try searching for `DataType` (e.g.), you get less helpful context:

![image](https://user-images.githubusercontent.com/160652/129386885-a3eda378-cebc-4f07-b559-b53cd30f8545.png)

2021-08-13 16:24 UTC, connec commented on sn_cmd_test_utilities/src/lib.rs
> +        let mut code = 0;
Nitpick: you can avoid the `mut` variable by assigning directly from the `if`:

```rust
let code = if let Some(c) = expect_exit_code {
    c
} else {
    0
};
```

In this case, it's even simpler – you can use `unwrap_or`:

```rust
let code = expect_exit_code.unwrap_or(0);
```

Opinion: I like to avoid `mut` if I can, since it would also allow for 'unexpected' modifications (not too likely in a small function like this, but I find it's better to keep to good practices).

2021-08-13 16:24 UTC, connec commented on resources/test-scripts/cli-tests
> +declare -a exit_codes
I guess this is left over from something fancier?

2021-08-13 16:24 UTC, connec commented on tests/cli_files.rs
> +    let _ = color_eyre::install();
Why install `color_eyre` in this test and not the others?

2021-08-13 16:24 UTC, connec commented on sn_cmd_test_utilities/src/lib.rs
>      pub fn safe_cmd(args: &[&str], expect_exit_code: Option<i32>) -> Result<process::Output> {
Suggestion: Not too pressing since it was already like this, but this could be a bit more ergonomic with an `IntoIterator` (as with [`assert_cmd::Command::args`](https://docs.rs/assert_cmd/2.0.0/assert_cmd/cmd/struct.Command.html#method.args)):

```suggestion
    pub fn safe_cmd(args: impl IntoIterator<Item = &str>, expect_exit_code: Option<i32>) -> Result<process::Output> {
```

This would allow calling with with any iterable of stringy things. E.g. from elsewhere in the PR:

```rust
    let slice: Vec<&str> = args.iter().map(|x| &**x).collect();
    safe_cmd(&slice, expect_exit_code)
```

Could become just:

```rust
    safe_cmd(args, expect_exit_code)
```

Similarly, arrays now implement `IntoIterator`, so sites like:

```rust
safe_cmd_stdout(&["files", "put", TEST_FILE, "--json"], Some(0))
```

Could become:

```rust
safe_cmd_stdout(["files", "put", TEST_FILE, "--json"], Some(0))
```

2021-08-16 14:10 UTC, jacderida commented on sn_cmd_test_utilities/src/lib.rs
> +    pub fn get_file_len(path: &str) -> Result<u64> {
Great suggestion, thanks. Fixed now.

2021-08-16 14:11 UTC, jacderida commented on sn_cmd_test_utilities/src/lib.rs
> +        Ok(len)
Yeah, the iterator use seems much more idiomatic, so this was another great suggestion. Thanks. Fixed now.

2021-08-16 14:11 UTC, jacderida commented on sn_cmd_test_utilities/src/lib.rs
> +    /// Runs safe with the arguments specified, with the option to assert on the exit code.
Thanks for pointing that out. Fixed.

2021-08-16 14:12 UTC, jacderida commented on sn_cmd_test_utilities/src/lib.rs
> +        let mut code = 0;
Good spot, that's much more concise. Thanks. Fixed now.

2021-08-16 14:12 UTC, jacderida commented on resources/test-scripts/cli-tests
> +declare -a exit_codes
Yeah sorry, that was a mistake. Removed now.

2021-08-16 14:12 UTC, jacderida commented on tests/cli_files.rs
> +    let _ = color_eyre::install();
Yeah, this was an oversight. Thanks. Fixed now.

2021-08-16 14:13 UTC, jacderida commented on sn_cmd_test_utilities/src/lib.rs
>      pub fn safe_cmd(args: &[&str], expect_exit_code: Option<i32>) -> Result<process::Output> {
Changed this and it made all the calling code cleaner. Thanks.

2021-08-16 14:32 UTC, bochaco submitted a review, later dismissed
Awesome job @jacderida , it seems tests read much better now!

2021-08-17 09:01 UTC, connec submitted a review, later dismissed
LGTM!

I did leave a couple of comments. If `itertools` isn't needed we probably should remove it before merging, but otherwise seems good to go!

The other ones about the `ctor`s are more informational/hypothetical, and I think we can leave 'em.

2021-08-20 20:17 UTC, dan-da commented on sn_cmd_test_utilities/src/lib.rs
> -        println!("Executing: safe {}", args.join(" "));
I think we want this println back.  It is super useful for knowing how a command was invoked when a test fails.

2021-08-20 20:44 UTC, dan-da commented on tests/cli_files_get.rs
> +/// Scenario: the `files get` command downloads a directory from the network to the specified path
I feel like these longer comments are somehow less clear "at a glance" than the originals -- which also enable easy comparison between the test cases.   A full description is nice and very good, but perhaps consider incorporating originals as a synopsis eg at top of each comment, eg:

```
synopsis
-----
description
```

if u don't agree that's fine... just a suggestion.

2021-08-20 20:53 UTC, jacderida commented on tests/cli_files_get.rs
> +/// Scenario: the `files get` command downloads a directory from the network to the specified path
Hi Dan, thanks for the feedback. Sure, no problem! Can add them back in.

2021-08-20 20:57 UTC, jacderida commented on sn_cmd_test_utilities/src/lib.rs
> -        println!("Executing: safe {}", args.join(" "));
This was removed because the `IntoIterator` doesn't have the `join` function.

If there's a failure, the `assert_cmd` outputs contains the arguments that the process was launched with, along with `stdout` and `stderr`. So we thought that was enough.

2021-08-21 02:21 UTC, dan-da commented on sn_cmd_test_utilities/src/lib.rs
> -        println!("Executing: safe {}", args.join(" "));
I would argue it is a step backward to not include the full command string in the output.  It used to behave in pretty much that fashion and when debugging an issue I often wanted to just re-run the exact command.  But it's painful to manually reconstruct from individual args.   The println() allows one to quickly copy/paste a command and exec it, which then allows to see additional output, etc.

Is it not possible to obtain (or construct) the full command string with this solution?

2021-08-21 14:32 UTC, jacderida commented on sn_cmd_test_utilities/src/lib.rs
> -        println!("Executing: safe {}", args.join(" "));
Yeah, it will definitely be possible to reconstruct the command. I'll get it sorted on Monday.

2021-08-21 14:33 UTC, jacderida commented on sn_cmd_test_utilities/Cargo.toml
> +itertools = "~0.10"
This was left in as a mistake. Removed in the most recent commit.

2021-08-21 14:33 UTC, jacderida commented on tests/cli_cat.rs
> +}
Moved this into the util lib. Thanks.

2021-08-23 16:46 UTC, jacderida commented on sn_cmd_test_utilities/src/lib.rs
> -        println!("Executing: safe {}", args.join(" "));
This was added back in.

2021-08-23 16:47 UTC, jacderida commented on tests/cli_files_get.rs
> +/// Scenario: the `files get` command downloads a directory from the network to the specified path
These comments were added back in.

2021-08-23 16:51 UTC, merged